<script language="JavaScript">
function viewSource() {window.location="view-source:"+window.location} </script>

View source:
[<a target=_blank href="/jang/books/webprog/common/showcode.asp?source=<%=Request.ServerVariables("PATH_INFO")%>">Server script</a>]
[<a href="javascript:viewSource()">Client script</a>]
<br>
Back to <a href="..">JavaScript 線上中文手冊</a>

<a href="/jang/sandbox/asp/lib/editfile.asp?FileName=<%=Request.ServerVariables("PATH_INFO")%>"><img align=right border=0 src="/jang/graphics/invisible.gif"></a>

</body>
</html>
