<head>
<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=big5">
<title>Web Technologies and Applications</title>
<style> td {font-family: "標楷體", "helvetica,arial", "Tahoma";}</style>
<style> A{text-decoration:none} </style>
</head>
<body bgcolor="#FFFF99">

<script language="JavaScript">
function settitle(title) {
	blankline();
	document.write("<center>");
	document.write("<table border=1>");
	document.write("<tr>");
	document.write("<td bgcolor=yellow align=center>");
	document.write("<font size=+3>"+title+"</font></td>");
	document.write("</tr>");
	document.write("</table>");
	document.write("</center>");
	blankline();
}

function blankline() {
	document.write("<table><tr><td>&nbsp;</table>");
}
</script>
